[package]
name = "jury-tui"
description = "Keyboard-first terminal interface for Jury"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
publish = false

[dependencies]
jury-core = { path = "../jury-core" }
jury-protected = { path = "../jury-protected" }

[target.'cfg(unix)'.dev-dependencies]
rlimit = "=0.11.0"

[lints]
workspace = true
