[workspace]
members = [
    "crates/jury",
    "crates/jury-core",
    "crates/jury-filesystem",
    "crates/jury-process",
    "crates/jury-protected",
    "crates/jury-protocol",
    "crates/jury-tui",
    "crates/jury-witness",
]
resolver = "3"
exclude = ["third_party/sanitization", "third_party/darwin-process-info"]

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.90"
license = "Elastic-2.0"
repository = "https://github.com/bpcakes/jury"
readme = "README.md"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
cognitive_complexity = "warn"
expect_used = "deny"
unwrap_used = "deny"

[profile.test]
opt-level = 1
debug-assertions = true
overflow-checks = true
